version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_clientes,ms_carrinho,ms_gt_itens,ms_pagamento,ms_autenticacao
    command: >
      bash -c '
        echo "CREATE DATABASE ms_clientes;" >> /docker-entrypoint-initdb.d/init.sql &&
        echo "CREATE DATABASE ms_carrinho;" >> /docker-entrypoint-initdb.d/init.sql &&
        echo "CREATE DATABASE ms_gt_itens;" >> /docker-entrypoint-initdb.d/init.sql &&
        echo "CREATE DATABASE ms_pagamento;" >> /docker-entrypoint-initdb.d/init.sql &&
        echo "CREATE DATABASE ms_autenticacao;" >> /docker-entrypoint-initdb.d/init.sql &&
        docker-entrypoint.sh postgres
      ' 
    ports:
      - "5432:5432"